"""Ajust validation fields

Revision ID: 1623b38f1d1c
Revises: 00ae2ab09305
Create Date: 2024-07-08 20:05:57.793341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1623b38f1d1c'
down_revision: Union[str, None] = '00ae2ab09305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
